#!/bin/bash
#PBS -l nodes=4:ppn=8
#PBS -N MITgcm_two_rivers

cd /storage/ioa/josue/MITgcm/article_run/run/

pwd

mpirun -np 32 -machinefile $PBS_NODEFILE ./mitgcmuv
#mpirun -np 8 ./mitgcmuv

date "+%H:%M:%S   %d/%m/%y"
